### PR TITLE
Fix upload error with Yii 1.1.16

### PR DESCRIPTION
**Pull request by gplaza**
fix error on upload with the new version of Jquery in Yii 1.1.16.

### CODE REVIEW

**Comment by Asgaroth** [comment]
does updating the jquery-fileupload library not fix the issue?

**Comment by Abdul0010** [comment]
works fine now thanks

**Comment by gplaza** [comment]
@Asgaroth : no, only update the jquery-fileupload not fix the issue.

**Comment by taobig** [comment]
thinks @gplaza, It works fine with Yii 1.1.16 now !

**Comment by xaratt** [comment]
Also "var that" should be fixed in line 284 for correct destroying.

**Pull request merged**
